import { Toaster } from 'react-hot-toast';
import './globals.css';
import AppProviders from './AppProviders';
import Header from '@/components/Header';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<AppProviders>
				<body>
					<Header />
					<main className="min-h-screen  flex flex-col items-center">{children}</main>
					<Toaster />
				</body>
			</AppProviders>
		</html>
	);
}
